import {
  TOKEN_SCHEMA_VERSION,
  type ComponentTokenDefinition,
  type ThemeTokenDocument,
  type ThemeTokenTree,
} from "./types.js";

export const WECHAT_SYSTEM_FONT =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif";

const systemComponents: Readonly<Record<string, ComponentTokenDefinition>> = {
  "component.legal.focus": {
    background: "{colors.surface}",
    borderColor: "{colors.borderStrong}",
    borderRadius: "{radius.sm}",
    borderStyle: "solid",
    borderWidth: 1,
    color: "{colors.textPrimary}",
    compatibilityLevel: "compatible",
    paddingBottom: "{spacing.lg}",
    paddingLeft: "{spacing.lg}",
    paddingRight: "{spacing.lg}",
    paddingTop: "{spacing.lg}",
    variant: "focus",
  },
  "divider.default": {
    borderColor: "{colors.border}",
    borderStyle: "solid",
    borderWidth: 1,
    marginBottom: "{spacing.lg}",
    marginTop: "{spacing.lg}",
    variant: "solid",
  },
  "heading.level1.default": {
    color: "{colors.textPrimary}",
    fontSize: "{typography.heading1Size}",
    fontWeight: "{typography.heading1Weight}",
    lineHeight: "{typography.heading1LineHeight}",
    marginBottom: "{spacing.headingBottom}",
    marginTop: "{spacing.headingTop}",
    variant: "plain",
  },
  "footer.brand.default": {
    color: "{colors.textMuted}",
    fontSize: "{typography.captionSize}",
    lineHeight: "{typography.captionLineHeight}",
    marginTop: "{spacing.section}",
    textAlign: "center",
    variant: "brand",
  },
  "heading.level2.default": {
    color: "{colors.textPrimary}",
    fontSize: "{typography.heading2Size}",
    fontWeight: "{typography.heading2Weight}",
    lineHeight: "{typography.heading2LineHeight}",
    marginBottom: "{spacing.headingBottom}",
    marginTop: "{spacing.headingTop}",
    variant: "plain",
  },
  "heading.level3.default": {
    color: "{colors.textPrimary}",
    fontSize: "{typography.heading3Size}",
    fontWeight: "{typography.heading3Weight}",
    lineHeight: "{typography.heading3LineHeight}",
    marginBottom: "{spacing.sm}",
    marginTop: "{spacing.lg}",
    variant: "plain",
  },
  "image.default": {
    borderColor: "{colors.border}",
    borderRadius: "{image.defaultRadius}",
    boxShadow: "{image.shadow}",
    marginBottom: "{image.defaultMarginBottom}",
    marginTop: "{image.defaultMarginTop}",
    variant: "plain",
  },
  "paragraph.default": {
    color: "{colors.textPrimary}",
    fontFamily: "{typography.fontFamilyWechat}",
    fontSize: "{typography.bodySize}",
    fontWeight: "{typography.bodyWeight}",
    letterSpacing: "{typography.bodyLetterSpacing}",
    lineHeight: "{typography.bodyLineHeight}",
    marginBottom: "{spacing.paragraphGap}",
    variant: "body",
  },
  "quote.default": {
    background: "{colors.surface}",
    borderColor: "{colors.primary}",
    borderStyle: "solid",
    borderWidth: 1,
    color: "{colors.textSecondary}",
    fontSize: "{typography.quoteSize}",
    paddingBottom: "{spacing.lg}",
    paddingLeft: "{spacing.lg}",
    paddingRight: "{spacing.lg}",
    paddingTop: "{spacing.lg}",
    variant: "softSurface",
  },
  "svg.default": {
    compatibilityLevel: "conditional",
    marginBottom: "{spacing.lg}",
    marginTop: "{spacing.lg}",
    variant: "staticFallback",
  },
};

export const SYSTEM_THEME_TOKENS = {
  schemaVersion: TOKEN_SCHEMA_VERSION,
  colors: {
    accent: "#C9A227",
    background: "#FFFFFF",
    border: "#EAECF0",
    borderStrong: "#D0D5DD",
    danger: "#B42318",
    primary: "#B42318",
    primaryDark: "#7A1712",
    primaryLight: "#FDECEC",
    secondary: "#344054",
    success: "#157F3D",
    surface: "#F9FAFB",
    surfaceStrong: "#F2F4F7",
    textMuted: "#98A2B3",
    textPrimary: "#1D2939",
    textSecondary: "#667085",
    warning: "#B54708",
  },
  typography: {
    bodyLetterSpacing: 0.3,
    bodyLineHeight: 1.8,
    bodySize: 16,
    bodyWeight: 400,
    captionLineHeight: 1.6,
    captionSize: 13,
    dataSize: 28,
    fontFamilyWechat: WECHAT_SYSTEM_FONT,
    heading1LineHeight: 1.45,
    heading1Size: 22,
    heading1Weight: 700,
    heading2LineHeight: 1.5,
    heading2Size: 19,
    heading2Weight: 700,
    heading3LineHeight: 1.55,
    heading3Size: 17,
    heading3Weight: 600,
    quoteSize: 16,
  },
  spacing: {
    contentPadding: 16,
    headingBottom: 14,
    headingTop: 28,
    lg: 16,
    md: 12,
    paragraphGap: 16,
    section: 36,
    sm: 8,
    xl: 24,
    xs: 4,
    xxl: 32,
  },
  radius: {
    lg: 12,
    md: 8,
    none: 0,
    pill: 999,
    sm: 4,
    xl: 18,
  },
  border: {
    leftAccent: "4px solid",
    medium: "2px solid",
    strong: "3px solid",
    thin: "1px solid",
  },
  shadow: {
    medium: "0 6px 20px rgba(16,24,40,0.10)",
    none: "none",
    soft: "0 4px 16px rgba(16,24,40,0.06)",
  },
  image: {
    border: "none",
    captionAlign: "center",
    captionColor: "{colors.textMuted}",
    captionSize: 13,
    defaultMarginBottom: 16,
    defaultMarginTop: 16,
    defaultRadius: 8,
    shadow: "{shadow.none}",
  },
  motion: {
    durationFast: 180,
    durationNormal: 320,
    durationSlow: 500,
    easingEmphasized: "cubic-bezier(0.2,0.8,0.2,1)",
    easingStandard: "ease-out",
  },
  compatibility: {
    allowComplexBackground: false,
    allowCustomFont: false,
    allowRiskyLayout: false,
    allowShadow: true,
    maxNestingDepth: 4,
  },
  components: systemComponents,
} as const satisfies ThemeTokenDocument & ThemeTokenTree;
